version: 2
jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:2.0-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      # Substitute build number for patch portion of version in project file
      - run:
          name: Update Version Number
          command: |
            sed -i "s/\(<VersionPrefix>[0-9]*\.[0-9]*\.\)\([0-9]*\)/\1$CIRCLE_BUILD_NUM/" ./SpecExpress.Core/SpecExpress.Core.csproj
      - run: 
          name: Build
          command: dotnet build 
      - run:
          name: Test
          command: dotnet test -v normal ./SpecExpress.Core.UnitTests/SpecExpress.Core.UnitTests.csproj
      - run:
          name: Deploy to Nuget (if alpha or release)
          command: |
              echo "Deploying!"
              if [[ "$CIRCLE_BRANCH" == alpha/* ]]; then
              dotnet pack --version-suffix alpha --output ./package
              export PACKAGE_FILE=$(ls /temp/SpecExpress.Core/package/*.nupkg)
              dotnet nuget push $PACKAGE_FILE -s $NUGET_URL -k $NUGET_API_KEY
              fi
              if [[ "$CIRCLE_BRANCH" == release/* ]]; then
              dotnet pack -c release --output ./package
              export PACKAGE_FILE=$(ls /temp/SpecExpress.Core/package/*.nupkg)
              dotnet nuget push $PACKAGE_FILE -s $NUGET_URL -k $NUGET_API_KEY
              fi