version: 2
jobs:
  build:
    branches:
      only:
        - /alpha\/.*/
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:2.0-sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet build 
      - run: |
          echo "Deploying $CIRCLE_BRANCH"
          export IS_ALPHA=[["$CIRCLE_BRANCH" == alpha/* ]]
          export IS_RELEASE=[["$CIRCLE_BRANCH" == release/* ]]
          echo $IS_ALPHA
          echo $IS_RELEASE
          if $IS_ALPHA; then
          dotnet pack --version-suffix alpha --output ./package
          export PACKAGE_FILE=$(ls ./package/*.nupkg)
          dotnet nuget push $PACKAGEFILE -s $NUGET_URL -k $NUGET_API_KEY
          fi
          if $IS_RELEASE; then
          dotnet pack --version-suffix alpha --output ./package
          export PACKAGE_FILE=$(ls ./package/*.nupkg)
          dotnet nuget push $PACKAGEFILE -s $NUGET_URL -k $NUGET_API_KEY
          fi